publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "scaled_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: ["0.785,0.1", "-1.57,0.3", "0.785,0.4", "0.785,0.5", "0.785,0.6",   "0.785,0.7"]
    pos2: ["0.0,0.1",   "-1.57,0.2", "0.0,0.3",   "-1.57,0.2", "0.0, 0.5",    "0.0,0.6"]
    pos3: ["0.0,0.1",   "-1.57,0.2", "0.0,0.3",   "-1.57,0.2", "-0.785, 0.5", "0.0,0.6"]
    pos4: ["0.0,0.1",   "-1.57,0.2", "0.0,0.3",   "-1.57,0.2", "0.0, 0.5",    "0.0, 0.5"]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint:  ["-3.14,-3.14", "3.14,3.14"]
      shoulder_lift_joint: ["-3.14,-3.14", "3.14,3.14"]
      elbow_joint:   ["-3.14,-3.14", "3.14,3.14"]
      wrist_1_joint: ["-3.14,-3.14", "3.14,3.14"]
      wrist_2_joint: ["-3.14,-3.14", "3.14,3.14"]
      wrist_3_joint: ["-3.14,-3.14", "3.14,3.14"]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: ["0.785,0.1", "-1.57,0.3", "0.785,0.4", "0.785,0.5", "0.785,0.6",   "0.785,0.7"]
    pos2: ["0.0,0.1",   "-1.57,0.2", "0.0,0.3",   "-1.57,0.2", "0.0, 0.5",    "0.0,0.6"]
    pos3: ["0.0,0.1",   "-1.57,0.2", "0.0,0.3",   "-1.57,0.2", "-0.785, 0.5", "0.0,0.6"]
    pos4: ["0.0,0.1",   "-1.57,0.2", "0.0,0.3",   "-1.57,0.2", "0.0, 0.5",    "0.0, 0.5"]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint:  ["-3.14,3.14", "-3.14,3.14"]
      shoulder_lift_joint: ["-3.14,3.14", "-3.14,3.14"]
      elbow_joint:   ["-3.14,3.14", "-3.14,3.14"]
      wrist_1_joint: ["-3.14,3.14", "-3.14,3.14"]
      wrist_2_joint: ["-3.14,3.14", "-3.14,3.14"]
      wrist_3_joint: ["-3.14,3.14", "-3.14,3.14"]
